apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30005
  selector:
    app: flask-pod
  type: NodePort
