# This is a basic workflow to help you get started with Actions

name: Push to Public

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout private repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main
          fetch-depth: 0

      - name: Generate App Token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Configure Git
        run: |
          git config --global user.name "DU Cloud Society App"
          git config --global user.email "du-cloud-soc+github-actions[bot]@users.noreply.github.com"

      # - name: Push to public repo
      #   env:
      #     PUBLIC_REPO_TOKEN: ${{ steps.generate-token.outputs.token }}
      #   run: |
      #     git remote add public-repo "https://x:${{ steps.generate-token.outputs.token }}@github.com/du-cloud-soc/cloud-workshops.git"
      #     git push public-repo main --force
      
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ steps.generate-token.outputs.token }}
          repository: du-cloud-soc/cloud-workshops
          force: true


